// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rikf5ZUwe40qkw7wPB8RYdXT06ZkQU4',
    appId: '1:699417994419:web:2a657a880bfe7bad0e7cc6',
    messagingSenderId: '699417994419',
    projectId: 'flutterapp-130ff',
    authDomain: 'flutterapp-130ff.firebaseapp.com',
    storageBucket: 'flutterapp-130ff.appspot.com',
    measurementId: 'G-CL7HFK87PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhwoDedLQI6ju0yV0GAylvojnYSz4y8jw',
    appId: '1:699417994419:android:30a412b63b23da000e7cc6',
    messagingSenderId: '699417994419',
    projectId: 'flutterapp-130ff',
    storageBucket: 'flutterapp-130ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWFxFctYD1Hy7sdTqVpE_B7oO_6vmn5hY',
    appId: '1:699417994419:ios:58f739fce6ee68690e7cc6',
    messagingSenderId: '699417994419',
    projectId: 'flutterapp-130ff',
    storageBucket: 'flutterapp-130ff.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWFxFctYD1Hy7sdTqVpE_B7oO_6vmn5hY',
    appId: '1:699417994419:ios:9d50890ba26c04df0e7cc6',
    messagingSenderId: '699417994419',
    projectId: 'flutterapp-130ff',
    storageBucket: 'flutterapp-130ff.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
